const BASE_FACTOR = 1000000n;
const BLOCKS_PER_ERA = 8000000n;
const NUMBER_OF_ERAS = 8n;
const PROTOTYPE_ISSUANCE = 130036019000n;
const FIRST_ERA_ISSUANCE_PER_BLOCK = (BASE_FACTOR * 128n) / 100n;
const LAST_BLOCK_OF_FIRST_ERA =
  BLOCKS_PER_ERA * FIRST_ERA_ISSUANCE_PER_BLOCK -
  PROTOTYPE_ISSUANCE / FIRST_ERA_ISSUANCE_PER_BLOCK;
const DEFAULT_FEE = 3000n;

module.exports = {
  BLOCKS_PER_ERA,
  LAST_BLOCK_OF_FIRST_ERA,
  NUMBER_OF_ERAS,
  BASE_FACTOR,
  DEFAULT_FEE,
  FIRST_ERA_ISSUANCE_PER_BLOCK,
};
